### ISSUE TITLE
How to use rename

### ISSUE THREAD

**Issue by MantieReid** [cenkalti/putio.py#48]
How do I use rename? 
`changename = client.File.rename('62650943', "testfile")`
I have tried using the following code above and nothing seems to work. 

I keep getting the following error each time I try using it. 
 `return self.client.request('/files/rename', method='POST',
AttributeError: 'str' object has no attribute 'client'`

How do I use rename?

**Comment by cenkalti** [comment]
Correct usage:
```py
f = client.File.get(62650943)
f.rename("new name")
```
